/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_jetty_setuid_SetUID_LibFilenameFilter */

#ifndef _Included_org_eclipse_jetty_setuid_SetUID_LibFilenameFilter
#define _Included_org_eclipse_jetty_setuid_SetUID_LibFilenameFilter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
