version: 2
updates:
  - package-ecosystem: "maven"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    target-branch: "jetty.toolchain.parent"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    target-branch: "jetty.toolchain.parent"
    directory: "/"
    schedule:
      interval: "weekly"